# .github/workflows/deploy.yml
name: Deploy FastAPI to AWS Lambda

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0
        
    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init
      
    - name: Terraform Plan
      working-directory: ./terraform
      run: terraform plan -var="api_key=${{ secrets.API_KEY }}"
      
    terraform import aws_lambda_function.fastapi_lambda fastapi-lambda
    terraform import aws_apigatewayv2_api.fastapi_gateway your-api-id


    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -auto-approve -var="api_key=${{ secrets.API_KEY }}"
      
    - name: Output API URL
      working-directory: ./terraform
      run: |
        API_URL=$(terraform output -raw api_gateway_url)
        
        # Wait a moment for deployment to be ready
        sleep 10

        # Test authenticated endpoint
        echo "Testing authenticated endpoint..."
        curl -f -H "X-API-Key: ${{ secrets.API_KEY }}" \
          "$API_URL/API/lambda/25"


        echo "🚀 API deployed at: $API_URL"
